apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-config-data-INST
  labels:
    type: local
    app: mongo
    target-service: mongo-config
spec:
  capacity:
    storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mongo-data/volume-config-INST
  persistentVolumeReclaimPolicy: Retain
  storageClassName: config-storage
