apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-INST
  labels:
    type: local
    app: zookeeper
    target-service: zookeeper
spec:
  capacity:
    storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/zookeeper-data/volume-INST
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-storage
