apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-DYNAMIC_INST
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "zookeeper"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOO_TICK_TIME
          value: "2000"
        - name: ZOO_INIT_LIMIT
          value: "10"
        - name: ZOO_SYNC_LIMIT
          value: "5"
        - name: ZOO_MAX_CLIENT_CNXNS
          value: "60"
        - name: ZOO_STANDALONE_ENABLED
          value: "false"
        - name: ZOO_AUTOPURGE_PURGEINTERVAL
          value: "12"
        - name: ZOO_AUTOPURGE_SNAPRETAINCOUNT
          value: "3"
        - name: ZOO_MY_ID
          value: "DYNAMIC_ID"
        - name: ZOO_SERVERS
          value: "DYNAMIC_SERVER_LIST"
        - name: ZOO_4LW_COMMANDS_WHITELIST
          value: "ruok"
        volumeMounts:
        - name: zookeeper-storage-claim
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "zookeeper-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
