apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  ports:
  - name: front
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31333
  selector:
    app: front
  type: NodePort
