apiVersion: v1
kind: Service
metadata:
  name: mongos-router-service
  labels:
    name: mongos-router
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongos-router
