apiVersion: v1
kind: Service
metadata:
  name: mongo-external
spec:
  ports:
  - name: mongo-external
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 31500
  selector:
    role: mongos-router
  type: NodePort

