apiVersion: v1
kind: Service
metadata:
  name: mongodb-configdb-service
  labels:
    name: mongo-configdb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo-configdb
